export default [
  {
    id: 20132937,
    node_id: "MDEwOlJlcG9zaXRvcnkyMDEzMjkzNw==",
    name: "repo",
    full_name: "source4code/repo",
    private: false,
    owner: {
      login: "source4code",
      id: 7348937,
      node_id: "MDQ6VXNlcjczNDg5Mzc=",
      avatar_url: "https://avatars3.githubusercontent.com/u/7348937?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/source4code",
      html_url: "https://github.com/source4code",
      followers_url: "https://api.github.com/users/source4code/followers",
      following_url: "https://api.github.com/users/source4code/following{/other_user}",
      gists_url: "https://api.github.com/users/source4code/gists{/gist_id}",
      starred_url: "https://api.github.com/users/source4code/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/source4code/subscriptions",
      organizations_url: "https://api.github.com/users/source4code/orgs",
      repos_url: "https://api.github.com/users/source4code/repos",
      events_url: "https://api.github.com/users/source4code/events{/privacy}",
      received_events_url: "https://api.github.com/users/source4code/received_events",
      type: "User",
      site_admin: false
    },
    html_url: "https://github.com/source4code/repo",
    description: "This repository contains all the source code for http://www.source4code.info",
    fork: true,
    url: "https://api.github.com/repos/source4code/repo",
    forks_url: "https://api.github.com/repos/source4code/repo/forks",
    keys_url: "https://api.github.com/repos/source4code/repo/keys{/key_id}",
    collaborators_url: "https://api.github.com/repos/source4code/repo/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/source4code/repo/teams",
    hooks_url: "https://api.github.com/repos/source4code/repo/hooks",
    issue_events_url: "https://api.github.com/repos/source4code/repo/issues/events{/number}",
    events_url: "https://api.github.com/repos/source4code/repo/events",
    assignees_url: "https://api.github.com/repos/source4code/repo/assignees{/user}",
    branches_url: "https://api.github.com/repos/source4code/repo/branches{/branch}",
    tags_url: "https://api.github.com/repos/source4code/repo/tags",
    blobs_url: "https://api.github.com/repos/source4code/repo/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/source4code/repo/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/source4code/repo/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/source4code/repo/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/source4code/repo/statuses/{sha}",
    languages_url: "https://api.github.com/repos/source4code/repo/languages",
    stargazers_url: "https://api.github.com/repos/source4code/repo/stargazers",
    contributors_url: "https://api.github.com/repos/source4code/repo/contributors",
    subscribers_url: "https://api.github.com/repos/source4code/repo/subscribers",
    subscription_url: "https://api.github.com/repos/source4code/repo/subscription",
    commits_url: "https://api.github.com/repos/source4code/repo/commits{/sha}",
    git_commits_url: "https://api.github.com/repos/source4code/repo/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/source4code/repo/comments{/number}",
    issue_comment_url: "https://api.github.com/repos/source4code/repo/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/source4code/repo/contents/{+path}",
    compare_url: "https://api.github.com/repos/source4code/repo/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/source4code/repo/merges",
    archive_url: "https://api.github.com/repos/source4code/repo/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/source4code/repo/downloads",
    issues_url: "https://api.github.com/repos/source4code/repo/issues{/number}",
    pulls_url: "https://api.github.com/repos/source4code/repo/pulls{/number}",
    milestones_url: "https://api.github.com/repos/source4code/repo/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/source4code/repo/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/source4code/repo/labels{/name}",
    releases_url: "https://api.github.com/repos/source4code/repo/releases{/id}",
    deployments_url: "https://api.github.com/repos/source4code/repo/deployments",
    created_at: "2014-05-24T15:37:47Z",
    updated_at: "2016-07-10T21:03:50Z",
    pushed_at: "2015-08-25T21:07:14Z",
    git_url: "git://github.com/source4code/repo.git",
    ssh_url: "git@github.com:source4code/repo.git",
    clone_url: "https://github.com/source4code/repo.git",
    svn_url: "https://github.com/source4code/repo",
    homepage: null,
    size: 826,
    stargazers_count: 9,
    watchers_count: 9,
    language: "Java",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 63,
    mirror_url: null,
    archived: false,
    open_issues_count: 0,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz"
    },
    forks: 63,
    open_issues: 0,
    watchers: 9,
    default_branch: "master",
    score: 64.33924
  }
];
